import type { CollectionSummary } from "./types";

export const MOCK_COLLECTIONS: CollectionSummary[] = [
  {
    id: "csharp-fundamentals",
    slug: "csharp-fundamentals",
    title: "C# Fundamentals Pack",
    subtitle: "Стартовый путь: синтаксис, типы, базовые конструкции.",
    taskCount: 12,
    totalMinutes: 150,
    progress: 75,
    accent: "purple",
    iconGlyph: "C#",
    iconTone: "purple",
  },
  {
    id: "algorithm-starter",
    slug: "algorithm-starter",
    title: "Algorithm Starter Pack",
    subtitle: "Алгоритмы и структуры, которые спросят на собесе.",
    taskCount: 14,
    totalMinutes: 190,
    progress: 60,
    accent: "gold",
    iconGlyph: "Σ",
    iconTone: "gold",
  },
  {
    id: "web-api-journey",
    slug: "web-api-journey",
    title: "Web API Journey",
    subtitle: "Собери production REST на ASP.NET Core пошагово.",
    taskCount: 16,
    totalMinutes: 260,
    progress: 40,
    accent: "cyan",
    iconGlyph: "API",
    iconTone: "cyan",
  },
  {
    id: "realtime-websockets",
    slug: "realtime-websockets",
    title: "Real-time Apps: WebSockets",
    subtitle: "Real-time с WebSockets и SignalR, от echo до presence.",
    taskCount: 9,
    totalMinutes: 120,
    progress: 25,
    accent: "green",
    iconGlyph: "⇆",
    iconTone: "green",
  },
];
