import type { TaskDetail, TaskSummary } from "./types";

export const MOCK_TASKS: TaskSummary[] = [
  {
    id: "two-sum",
    slug: "two-sum",
    title: "Two Sum",
    difficulty: "easy",
    topics: ["arrays", "hash-map"],
    language: "csharp",
    xpReward: 25,
    status: "solved",
    acceptanceRate: 92.4,
    solvedBy: 18420,
  },
  {
    id: "reverse-linked-list",
    slug: "reverse-linked-list",
    title: "Reverse Linked List",
    difficulty: "easy",
    topics: ["linked-list"],
    language: "csharp",
    xpReward: 25,
    status: "solved",
    acceptanceRate: 88.1,
    solvedBy: 12930,
  },
  {
    id: "valid-parentheses",
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "easy",
    topics: ["strings"],
    language: "csharp",
    xpReward: 25,
    status: "in-progress",
    acceptanceRate: 71.5,
    solvedBy: 9802,
  },
  {
    id: "merge-intervals",
    slug: "merge-intervals",
    title: "Merge Intervals",
    difficulty: "medium",
    topics: ["arrays"],
    language: "csharp",
    xpReward: 50,
    status: "not-started",
    acceptanceRate: 64.8,
    solvedBy: 6240,
  },
  {
    id: "lru-cache",
    slug: "lru-cache",
    title: "LRU Cache",
    difficulty: "medium",
    topics: ["hash-map", "linked-list"],
    language: "csharp",
    xpReward: 50,
    status: "not-started",
    acceptanceRate: 58.2,
    solvedBy: 4810,
  },
  {
    id: "binary-search",
    slug: "binary-search",
    title: "Binary Search",
    difficulty: "easy",
    topics: ["binary-search", "arrays"],
    language: "csharp",
    xpReward: 25,
    status: "perfect",
    acceptanceRate: 94.0,
    solvedBy: 14250,
  },
  {
    id: "longest-substring",
    slug: "longest-substring",
    title: "Longest Substring Without Repeating",
    difficulty: "medium",
    topics: ["strings", "hash-map"],
    language: "csharp",
    xpReward: 50,
    status: "in-progress",
    acceptanceRate: 55.9,
    solvedBy: 5314,
  },
  {
    id: "coin-change",
    slug: "coin-change",
    title: "Coin Change",
    difficulty: "medium",
    topics: ["dynamic-programming"],
    language: "csharp",
    xpReward: 50,
    status: "not-started",
    acceptanceRate: 51.2,
    solvedBy: 3120,
  },
  {
    id: "word-ladder",
    slug: "word-ladder",
    title: "Word Ladder",
    difficulty: "hard",
    topics: ["graphs", "strings"],
    language: "csharp",
    xpReward: 100,
    status: "not-started",
    acceptanceRate: 38.4,
    solvedBy: 1208,
  },
  {
    id: "n-queens",
    slug: "n-queens",
    title: "N-Queens",
    difficulty: "hard",
    topics: ["dynamic-programming"],
    language: "csharp",
    xpReward: 100,
    status: "not-started",
    acceptanceRate: 42.7,
    solvedBy: 1840,
  },
  {
    id: "median-of-two-arrays",
    slug: "median-of-two-arrays",
    title: "Median of Two Sorted Arrays",
    difficulty: "hard",
    topics: ["binary-search", "arrays"],
    language: "csharp",
    xpReward: 100,
    status: "not-started",
    acceptanceRate: 35.0,
    solvedBy: 982,
  },
  {
    id: "min-depth-of-tree",
    slug: "min-depth-of-tree",
    title: "Minimum Depth of Binary Tree",
    difficulty: "easy",
    topics: ["trees"],
    language: "csharp",
    xpReward: 25,
    status: "not-started",
    acceptanceRate: 82.6,
    solvedBy: 8740,
  },
];

const TWO_SUM_STARTER = [
  "using System;",
  "using System.Collections.Generic;",
  "",
  "public class Solution",
  "{",
  "    public int[] TwoSum(int[] nums, int target)",
  "    {",
  "        var map = new Dictionary<int, int>();",
  "",
  "        for (int i = 0; i < nums.Length; i++)",
  "        {",
  "            int complement = target - nums[i];",
  "            if (map.ContainsKey(complement))",
  "                return new int[] { map[complement], i };",
  "            map[nums[i]] = i;",
  "        }",
  "",
  "        return new int[0];",
  "    }",
  "}",
];

export const MOCK_TASK_DETAIL: Record<string, TaskDetail> = {
  "two-sum": {
    ...(MOCK_TASKS.find((t) => t.id === "two-sum") as TaskSummary),
    description:
      "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input has exactly one solution, and you may not use the same element twice.",
    examples: [
      {
        input: "nums = [2, 7, 11, 15], target = 9",
        output: "[0, 1]",
        explanation: "Because nums[0] + nums[1] == 9, we return [0, 1].",
      },
      {
        input: "nums = [3, 2, 4], target = 6",
        output: "[1, 2]",
      },
      {
        input: "nums = [3, 3], target = 6",
        output: "[0, 1]",
      },
    ],
    constraints: [
      "2 <= nums.length <= 10^4",
      "-10^9 <= nums[i] <= 10^9",
      "-10^9 <= target <= 10^9",
      "Only one valid answer exists.",
    ],
    starterCode: TWO_SUM_STARTER,
    hints: [
      "A naive O(n²) approach checks every pair — fine for n ≤ 1000.",
      "Use a hash map to store the complement of each value in one pass.",
    ],
  },
};

export function getTaskBySlug(slug: string): TaskDetail | undefined {
  // Phase 0 visual scaffold: only `two-sum` has full detail; fall back to
  // synthesizing one from the summary so the page never 404s during dev.
  if (MOCK_TASK_DETAIL[slug]) return MOCK_TASK_DETAIL[slug];
  const summary = MOCK_TASKS.find((t) => t.slug === slug);
  if (!summary) return undefined;
  return {
    ...summary,
    description: "Task description coming soon.",
    examples: [],
    constraints: [],
    starterCode: TWO_SUM_STARTER,
    hints: [],
  };
}
