import type { TaskDetail, TaskSummary } from "./types";

/*
 * Phase 0 mock catalog — 12 hand-picked tasks that match the visible rows of
 * the arena reference (docs/VISUAL.md, "Arena page reference"). The set is
 * deliberately *not* LeetCode-shaped: it spans C# fundamentals → ASP.NET Core
 * → WebSockets → EF Core so the topic / format / status filters look meaningful
 * out of the box.
 */
export const MOCK_TASKS: TaskSummary[] = [
  {
    id: "variables-and-types",
    slug: "variables-and-types",
    title: "Variables and Types",
    shortDescription:
      "Изучи переменные, value/reference типы и базовые операции.",
    difficulty: "easy",
    topics: ["csharp-basics", "fundamentals"],
    language: "csharp",
    xpReward: 10,
    estimatedMinutes: 15,
    popularity: 92,
    status: "solved",
    format: "single",
    iconGlyph: "C#",
    iconTone: "purple",
    acceptanceRate: 92.4,
    solvedBy: 18420,
  },
  {
    id: "loops-arena",
    slug: "loops-arena",
    title: "Loops Arena",
    shortDescription:
      "Освой for, while и do-while на практических заданиях.",
    difficulty: "easy",
    topics: ["csharp-basics", "control-flow"],
    language: "csharp",
    xpReward: 10,
    estimatedMinutes: 20,
    popularity: 89,
    status: "solved",
    format: "single",
    iconGlyph: "∞",
    iconTone: "cyan",
    acceptanceRate: 88.1,
    solvedBy: 12930,
  },
  {
    id: "linq-basics",
    slug: "linq-basics",
    title: "LINQ Basics",
    shortDescription:
      "Фильтруй, проецируй и сортируй коллекции с помощью LINQ.",
    difficulty: "medium",
    topics: ["linq", "collections"],
    language: "csharp",
    xpReward: 20,
    estimatedMinutes: 25,
    popularity: 85,
    status: "in-progress",
    format: "single",
    iconGlyph: "λ",
    iconTone: "pink",
    acceptanceRate: 71.5,
    solvedBy: 9802,
  },
  {
    id: "two-sum",
    slug: "two-sum",
    title: "Two Sum",
    shortDescription:
      "Найди два индекса, сумма значений которых равна заданной цели.",
    difficulty: "medium",
    topics: ["algorithms", "array"],
    language: "csharp",
    xpReward: 25,
    estimatedMinutes: 30,
    popularity: 95,
    status: "not-started",
    format: "single",
    iconGlyph: "Σ",
    iconTone: "blue",
    acceptanceRate: 92.4,
    solvedBy: 18420,
  },
  {
    id: "stack-and-queue-basics",
    slug: "stack-and-queue-basics",
    title: "Stack and Queue Basics",
    shortDescription:
      "Реализуй стек и очередь, реши задачи на их основе.",
    difficulty: "medium",
    topics: ["data-structures", "collections"],
    language: "csharp",
    xpReward: 20,
    estimatedMinutes: 25,
    popularity: 82,
    status: "not-started",
    format: "single",
    iconGlyph: "≡",
    iconTone: "purple",
    acceptanceRate: 64.8,
    solvedBy: 6240,
  },
  {
    id: "build-your-first-web-api",
    slug: "build-your-first-web-api",
    title: "Build Your First Web API",
    shortDescription:
      "Создай простой REST API на ASP.NET Core с одним ресурсом.",
    difficulty: "medium",
    topics: ["aspnet-core", "web-api"],
    language: "csharp",
    xpReward: 30,
    estimatedMinutes: 40,
    popularity: 90,
    status: "not-started",
    format: "mini-quest",
    iconGlyph: "API",
    iconTone: "cyan",
    acceptanceRate: 58.2,
    solvedBy: 4810,
  },
  {
    id: "crud-with-aspnet-core",
    slug: "crud-with-aspnet-core",
    title: "CRUD with ASP.NET Core",
    shortDescription:
      "Собери полноценный CRUD с валидацией и маршрутизацией.",
    difficulty: "hard",
    topics: ["aspnet-core", "web-api"],
    language: "csharp",
    xpReward: 40,
    estimatedMinutes: 60,
    popularity: 88,
    status: "locked",
    unlockHint: "Заверши задачу #6",
    format: "mini-quest",
    iconGlyph: "⌘",
    iconTone: "green",
    acceptanceRate: 55.9,
    solvedBy: 5314,
  },
  {
    id: "websocket-chat-echo",
    slug: "websocket-chat-echo",
    title: "WebSocket Chat Echo",
    shortDescription:
      "Подними real-time эхо-чат на WebSockets / SignalR.",
    difficulty: "hard",
    topics: ["websockets", "real-time"],
    language: "csharp",
    xpReward: 40,
    estimatedMinutes: 45,
    popularity: 86,
    status: "locked",
    unlockHint: "Заверши задачу #6",
    format: "mini-quest",
    iconGlyph: "⇆",
    iconTone: "pink",
    acceptanceRate: 51.2,
    solvedBy: 3120,
  },
  {
    id: "async-await-mission",
    slug: "async-await-mission",
    title: "Async Await Mission",
    shortDescription:
      "Разберись с async/await и неблокирующим кодом.",
    difficulty: "medium",
    topics: ["async", "concurrency"],
    language: "csharp",
    xpReward: 25,
    estimatedMinutes: 30,
    popularity: 84,
    status: "not-started",
    format: "single",
    iconGlyph: "⚡",
    iconTone: "gold",
    acceptanceRate: 64.0,
    solvedBy: 5840,
  },
  {
    id: "ef-core-filtering-quest",
    slug: "ef-core-filtering-quest",
    title: "EF Core Filtering Quest",
    shortDescription:
      "Делай выборки с EF Core: eager loading, фильтры, проекции.",
    difficulty: "hard",
    topics: ["ef-core", "database"],
    language: "csharp",
    xpReward: 40,
    estimatedMinutes: 50,
    popularity: 80,
    status: "locked",
    unlockHint: "Заверши задачу #6",
    format: "mini-quest",
    iconGlyph: "DB",
    iconTone: "blue",
    acceptanceRate: 49.0,
    solvedBy: 2210,
  },
  {
    id: "gc-probe",
    slug: "gc-probe",
    title: "Garbage Collection Probe",
    shortDescription:
      "Замерь поколения GC и спровоцируй сборку без LoH-fragmentation.",
    difficulty: "hard",
    topics: ["oop", "fundamentals"],
    language: "csharp",
    xpReward: 50,
    estimatedMinutes: 55,
    popularity: 78,
    status: "not-started",
    format: "boss",
    iconGlyph: "♻",
    iconTone: "green",
    acceptanceRate: 42.7,
    solvedBy: 1840,
  },
  {
    id: "parallel-pipeline",
    slug: "parallel-pipeline",
    title: "Parallel Pipeline",
    shortDescription:
      "Построй конвейер на TPL Dataflow: backpressure, отмена, ошибки.",
    difficulty: "hard",
    topics: ["concurrency", "async"],
    language: "csharp",
    xpReward: 60,
    estimatedMinutes: 70,
    popularity: 74,
    status: "not-started",
    format: "boss",
    iconGlyph: "∥",
    iconTone: "red",
    acceptanceRate: 38.4,
    solvedBy: 1208,
  },
];

const TWO_SUM_STARTER = [
  "using System;",
  "using System.Collections.Generic;",
  "",
  "public class Solution",
  "{",
  "    public int[] TwoSum(int[] nums, int target)",
  "    {",
  "        var map = new Dictionary<int, int>();",
  "",
  "        for (int i = 0; i < nums.Length; i++)",
  "        {",
  "            int complement = target - nums[i];",
  "            if (map.ContainsKey(complement))",
  "                return new int[] { map[complement], i };",
  "            map[nums[i]] = i;",
  "        }",
  "",
  "        return new int[0];",
  "    }",
  "}",
];

export const MOCK_TASK_DETAIL: Record<string, TaskDetail> = {
  "two-sum": {
    ...(MOCK_TASKS.find((t) => t.id === "two-sum") as TaskSummary),
    description:
      "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input has exactly one solution, and you may not use the same element twice.",
    examples: [
      {
        input: "nums = [2, 7, 11, 15], target = 9",
        output: "[0, 1]",
        explanation: "Because nums[0] + nums[1] == 9, we return [0, 1].",
      },
      {
        input: "nums = [3, 2, 4], target = 6",
        output: "[1, 2]",
      },
      {
        input: "nums = [3, 3], target = 6",
        output: "[0, 1]",
      },
    ],
    constraints: [
      "2 <= nums.length <= 10^4",
      "-10^9 <= nums[i] <= 10^9",
      "-10^9 <= target <= 10^9",
      "Only one valid answer exists.",
    ],
    starterCode: TWO_SUM_STARTER,
    hints: [
      "A naive O(n²) approach checks every pair — fine for n ≤ 1000.",
      "Use a hash map to store the complement of each value in one pass.",
    ],
  },
};

export function getTaskBySlug(slug: string): TaskDetail | undefined {
  if (MOCK_TASK_DETAIL[slug]) return MOCK_TASK_DETAIL[slug];
  const summary = MOCK_TASKS.find((t) => t.slug === slug);
  if (!summary) return undefined;
  return {
    ...summary,
    description: "Task description coming soon.",
    examples: [],
    constraints: [],
    starterCode: TWO_SUM_STARTER,
    hints: [],
  };
}

/* Catalog headline number shown at the top of the table (e.g. "312 вызовов
 * найдено"). Picked to read like an active platform; not derived from
 * MOCK_TASKS, which only carries the 12 currently-rendered samples. */
export const MOCK_TOTAL_TASKS = 312;
